"""new rooms table

Revision ID: a3318981a10d
Revises: d91f8f28a25b
Create Date: 2026-06-06 10:03:53.020554

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a3318981a10d"
down_revision: str | Sequence[str] | None = "d91f8f28a25b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rooms")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rooms",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("time_slot", sa.VARCHAR(length=10), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
