"""create new rooms table

Revision ID: c6236a129b7c
Revises: a3318981a10d
Create Date: 2026-06-06 10:24:52.884882

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "c6236a129b7c"
down_revision: str | Sequence[str] | None = "a3318981a10d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
