"""Create rooms

Revision ID: d91f8f28a25b
Revises: 3ecdb2db5a4a
Create Date: 2026-06-04 15:00:15.546841

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "d91f8f28a25b"
down_revision: str | Sequence[str] | None = "3ecdb2db5a4a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
