"""new final rooms table migration

Revision ID: f5254f19952a
Revises: c6236a129b7c
Create Date: 2026-06-06 11:08:31.325821

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "f5254f19952a"
down_revision: str | Sequence[str] | None = "c6236a129b7c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
